# Generated by Django 4.2.6 on 2023-11-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_activitylog_goals_user_delete_teacher_goals_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.IntegerField(),
        ),
    ]
