# Generated by Django 4.2.6 on 2023-11-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_alter_user_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Goal',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.TextField(),
        ),
    ]
