# Generated by Django 4.2.6 on 2023-11-04 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_alter_activitylog_description_alter_goal_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='durations_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='frequency',
            field=models.TextField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.TextField(choices=[('distance', 'Distance'), ('time', 'Time')]),
        ),
    ]
