# Generated by Django 4.2.6 on 2023-11-05 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_alter_activitylog_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 4, 12, 9, 450307)),
        ),
        migrations.AlterField(
            model_name='goal',
            name='activity',
            field=models.TextField(choices=[('run', 'Run'), ('bike', 'Bike'), ('swim', 'Swim')]),
        ),
    ]
